version: "3.3"
services:
  mysql-server:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_pass}
      MYSQL_DATABASE: mydb
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_pass}
  django-app:
    build: ./dev/
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      mysql_user: ${mysql_user}
      mysql_pass: ${mysql_pass}
      django_adminpass: ${django_adminpass}
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql-server
    command: ["./start-dev"]
