#!/bin/bash

mysql_ready() {
        mysqladmin ping --host=mysql-server --user=root --password=MYSQL_ROOT_PASSWORD > /dev/null 2>&1
    }

while !(mysql_ready)
do
   sleep 5
   echo "waiting for mysql to continue..."
done
echo "creating static dir"
mkdir -p /usr/src/static
echo "copying data"
# mysql --host=mysql-server --user=${mysql_user} --password=${mysql_pass} mydb  < beauty-backup-2020-07-27.sql
# pip install --upgrade pip
# pip install -r requirements.txt
python manage.py makemigrations  --no-input --settings=project.settings_dev
python manage.py migrate  --no-input --settings=project.settings_dev
# python manage.py makemigrations app --no-input --merge
# python manage.py migrate app --no-input
# python manage.py makemigrations api --no-input --merge
# python manage.py migrate api --no-input
python manage.py collectstatic --no-input --settings=project.settings_dev
python manage.py showmigrations --settings=project.settings_dev
python manage.py initadmin --settings=project.settings_dev
python manage.py runserver 0.0.0.0:8000 --settings=project.settings_dev
# $(ip a | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep 172.18 | head -1):8090 #test
# uwsgi --ini conf.ini
